### PR TITLE
fix(api): shutdown listners gracefully close

### LINKED ISSUE #899: [BUG] The e2e tests don't correctly shutdown
It appears that the scheduler service isn't correctly being shutdown when the api is shutdown.  This is most obvious during e2e tests.  I believe this stems from the server under test being run in a subprocess, and the lack of cleanup of the scheduler in the `gracefulShutdown` function in apps/api/src/index.ts.

See below for the output I see after tests are finished:

```
🧹 Cleaning up test environment...
🕒 Clearing all scheduler timers...
[SchedulerService] Clearing all 0 global timers
🛑 Stopping server...
Stopping server...
Killing server process with PID: 614427
Server stopped
Checking for existing servers on ports 3001 and 3003...

[SIGTERM] Received shutdown signal, closing servers gracefully...
Main server closed
Metrics server closed
{"traceId":"background-task","type":"db","operation":"SELECT","status":"success","timestamp":"2025-07-17T15:41:01.031Z","queryPreview":"select \"trading_comps\".\"trading_competitions\".\"cross_chain_trading_type\", \"competitions\".\"id\", \"comp","queryTruncated":true}
{"traceId":"background-task","type":"db","operation":"SELECT","status":"success","timestamp":"2025-07-17T15:41:01.033Z","queryPreview":"select \"trading_comps\".\"trading_competitions\".\"cross_chain_trading_type\", \"competitions\".\"id\", \"comp","queryTruncated":true}
[SchedulerService] No active competition, skipping portfolio snapshots
Successfully killed existing server processes.
🔌 Closing database connection...
Database manager reset (connection maintained for app use)
✅ Test environment cleaned up
joe@joe-Precision-5550:~/Workspaces/textile/github/js-recall/apps/api$ {"traceId":"background-task","type":"db","operation":"SELECT","status":"success","timestamp":"2025-07-17T15:41:03.034Z","queryPreview":"select \"trading_comps\".\"trading_competitions\".\"cross_chain_trading_type\", \"competitions\".\"id\", \"comp","queryTruncated":true}
[SchedulerService] No active competition, skipping portfolio snapshots
{"traceId":"background-task","type":"db","operation":"SELECT","status":"success","timestamp":"2025-07-17T15:41:05.036Z","queryPreview":"select \"trading_comps\".\"trading_competitions\".\"cross_chain_trading_type\", \"competitions\".\"id\", \"comp","queryTruncated":true}
[SchedulerService] No active competition, skipping portfolio snapshots
{"traceId":"background-task","type":"db","operation":"SELECT","status":"success","timestamp":"2025-07-17T15:41:07.037Z","queryPreview":"select \"trading_comps\".\"trading_competitions\".\"cross_chain_trading_type\", \"competitions\".\"id\", \"comp","queryTruncated":true}
[SchedulerService] No active competition, skipping portfolio snapshots
{"traceId":"background-task","type":"db","operation":"SELECT","status":"success","timestamp":"2025-07-17T15:41:09.039Z","queryPreview":"select \"trading_comps\".\"trading_competitions\".\"cross_chain_trading_type\", \"competitions\".\"id\", \"comp","queryTruncated":true}
[SchedulerService] No active competition, skipping portfolio snapshots
Forcing exit after timeout


joe@joe-Precision-5550:~/Workspaces/textile/github/js-recall/apps/api$ 
```

### PR DESCRIPTION
**Pull request by joewagner**
fixes #899

### CODE REVIEW

File: apps/api/src/index.ts [hunk 1]
```diff
@@ -275,26 +275,28 @@ const mainServer = app.listen(PORT, "0.0.0.0", () => {
 // Start dedicated metrics server on separate port
 const metricsServer = startMetricsServer();
 
+let shuttingDown = false;
```
Comment (joewagner) [inline apps/api/src/index.ts:278]: I'm not sure how other systems work, but  when you hit control+c on Ubuntu the sigint listener is called twice, so I needed to add a gaurd.

File: apps/api/src/index.ts [hunk 2]
```diff
@@ -275,26 +275,28 @@ const mainServer = app.listen(PORT, "0.0.0.0", () => {
...
+
   console.log(
     `\n[${signal}] Received shutdown signal, closing servers gracefully...`,
   );
 
   // Close both servers
   mainServer.close(() => {
-    console.log("Main server closed");
-  });
+    console.log("[Shutdown] Main server closed");
```
Comment (joewagner) [inline apps/api/src/index.ts:290]: This function is **not** async, and neither is the execution of these callbacks.  This is a bit of a stylistic choice so we can definitely change if folks prefer that existing way.

File: apps/api/src/index.ts [hunk 3]
```diff
@@ -275,26 +275,28 @@ const mainServer = app.listen(PORT, "0.0.0.0", () => {
...
 
-  metricsServer.close(() => {
-    console.log("Metrics server closed");
-  });
+    metricsServer.close(() => {
+      console.log("[Shutdown] Metrics server closed");
 
-  // Force exit after timeout if graceful shutdown fails
-  setTimeout(() => {
```
Comment (joewagner) [inline apps/api/src/index.ts:294]: This comment and use of setTimeout is kind of confusing since the only thing keeping the process running is waiting for the timeout, and it will always wait.  So it's not exactly force exiting, it's forcing the process to stay running. 
Instead of this we can just use `process.exit(0)` since the callbacks all execute sync.

**Review by joewagner — COMMENTED** [review]
@ukstv I took a stab at fixing this since it's been bugging me while doing local testing.  If you have something else that's better in the works we can close this.

**Comment by joewagner** [comment]
> if you run the `setup:all` script with the code on `main`, you'll see these errors happen:
> 
> ```
> [SIGINT] Received shutdown signal, closing servers gracefully...
> Main server closed
> Metrics server closed
> 
> [SIGINT] Received shutdown signal, closing servers gracefully...
> Main server closed
> Metrics server closed
> ```
> 
> i tested this branch's behavior, and it makes those go away....so i'm personally down to give this approach a try because it seems to also fix the problem on mac.
> 
> note: if i use the bugbug "Fix in Cursor", it gives me this tweak:
> 
> ```ts
> // Graceful shutdown handler
> const gracefulShutdown = async (signal: string) => {
>   if (shuttingDown) return;
>   shuttingDown = true;
> 
>   console.log(
>     `\n[${signal}] Received shutdown signal, closing servers gracefully...`,
>   );
> 
>   // Set a timeout to force exit if graceful shutdown fails
>   const forceExitTimeout = setTimeout(() => {
>     console.error("[Shutdown] Forcing exit after timeout");
>     process.exit(1);
>   }, 10000);
> 
>   // Close both servers
>   mainServer.close(() => {
>     console.log("[Shutdown] Main server closed");
> 
>     metricsServer.close(() => {
>       console.log("[Shutdown] Metrics server closed");
> 
>       services.stopSchedulers();
> 
>       clearTimeout(forceExitTimeout);
>       process.exit(0);
>     });
>   });
> };
> ```

Nice! this is better

**Review by dtbuchholz — APPROVED** [review]
